### ISSUE TITLE
Out of memory (allocated 509607936) (tried to allocate 501223424 bytes)

### ISSUE THREAD

**Issue by waleedmazhar** [pallant/laravel-aws-cognito-auth#14]
Hi Guys,

I am getting following error even I use php memory limit to -1 (no limit)
(1/1) FatalErrorException  Out of memory (allocated 509607936) (tried to allocate 501223424 bytes)
in HomeController.php (line 36)

`try {
    Auth::attempt([
        'email' => 'pppppp@live.com',
        'password' => 'pppppp',
    ], false, AWS_COGNITO_AUTH_THROW_EXCEPTION);
} catch (\Pallant\LaravelAwsCognitoAuth\AuthAttemptException $e) {
    $response = $e->getResponse();
var_export($response);
    // Handle error...
}`

Any suggestion?

thanks in advance

**Comment by ArranJacques** [comment]
Hi

The code snippet you've included should work fine and does so in my tests. Can you include all your controller code, at least down to line 36 on which the error is occurring.

Thanks
