### ISSUE TITLE
Dependency on deprecation

### ISSUE THREAD

**Issue by kevinyea** [pallant/laravel-aws-cognito-auth#15]
Hi
I was altering an existing app on Laravel 5.5.4. However, I'm unable to follow the steps due to a missing file (config/aws-cognito-auth.php). There is some information which seems relevant [here](https://github.com/aws/aws-sdk-php-laravel/issues/115).
Laravel Deprecation issue with the AWS SDK as found [here](https://github.com/aws/aws-sdk-php/issues/1534)
Can you advise if it is me or some workaround for this issue.
Many thanks
Kevin

**Comment by ArranJacques** [comment]
Hi

Sorry for the slow response and I'm not sure if this will still be relevant for you but you can create the file manually if it's failing to publish when you run:

php artisan vendor:publish --provider="Pallant\LaravelAwsCognitoAuth\ServiceProvider"

To do so create a file called `aws-cognito-auth.php` in your `config` directory and then copy the contents of the file linked to below and add them to your config file.

https://github.com/ArranJacques/laravel-aws-cognito-auth/blob/master/src/config/aws-cognito-auth.php

That should resolve the issue for you and I'll have a look into why it might not be publishing when running the Artisan commands.

Thanks
