### ISSUE TITLE
Configuration file creation

### ISSUE THREAD

**Issue by Arkango** [pallant/laravel-aws-cognito-auth#16]
I did every pass of the guide but this file (aws-cognito-auth.php) isn't created 
and i haven't any erro on the terminal when i published them

Open config/aws-cognito-auth.php and add your AWS Cognito User Pool's id, and User Pool App's client-id.

**Comment by ArranJacques** [comment]
Hi

You can create the file manually if it's failing to publish when you run:

`php artisan vendor:publish --provider="Pallant\LaravelAwsCognitoAuth\ServiceProvider"`

To do so create a file called `aws-cognito-auth.php` in your `config` directory and then copy the contents of the file linked to below and add them to your config file.

https://github.com/ArranJacques/laravel-aws-cognito-auth/blob/master/src/config/aws-cognito-auth.php

That should resolve the issue for you and I'll have a look into why it might not be publishing when running the Artisan commands.

Thanks
