### ISSUE TITLE
Sync attributes

### ISSUE THREAD

**Issue by zeroiszero** [pallant/laravel-aws-cognito-auth#19]
is there any option to allow sync attributes from aws cognito response ? or handling the user access based on the groups in cognito...

something like this: https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth.md#syncing-attributes

**Comment by ArranJacques** [comment]
At this point no there is not. The package purely focuses on authenticating users. Any syncing of attributes or additional permission checks will need to be done manually.

This is something that I'm thinking of adding though in the future as I think it could be useful.
