### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by eric0324** [pallant/laravel-aws-cognito-auth#23]
When i try to login I get the following error:

```
Too few arguments to function Illuminate\Auth\Events\Attempting::__construct(), 2 passed in /Applications/AMPPS/www/web/vendor/pallant/laravel-aws-cognito-auth/src/AwsCognitoIdentityGuard.php on line 773 and exactly 3 expected
```

I think it may be a problem with my AWS COGNITO settings.

So, I check it...

```
AWS_ACCESS_KEY_ID="xxxxxx"
AWS_SECRET_ACCESS_KEY="xxxxx"
AWS_REGION="ap-southeast-1"
AWS_COGNITO_IDENTITY_POOL_ID="xxxxx"
AWS_COGNITO_IDENTITY_APP_CLIENT_ID="xxxxxx"
```
Did not find any problems... :'(

Please help me understand what might cause this error.

Thanks.

**Comment by eizzn** [comment]
I see the same issue
digging in revealed that this plugin needs an update for laravel 5.7.
it seemed to work again when I downgraded laravel to 5.6.  the exception went away but I still have not successfully logged in
