### ISSUE TITLE
Laravel 5.5 compatibility

### ISSUE THREAD

**Issue by gabrielef** [pallant/laravel-aws-cognito-auth#7]
Hi,
have you already tested the compatibility with Laravel 5.5?

Thank you
Gabriele

**Comment by sparky-dog** [comment]
I've encountered the same compatibility issue too.
it's telling me that it requires Laravel v.5.4x ....

**Comment by ArranJacques** [comment]
Hi

No I haven't had a chance to test it yet. I'm going to try and test it on 5.5 some point today or tomorrow and will address any compatibility issues.

Thanks

**Comment by getafixx** [comment]
yes I would also *really* like to see this also for Laravel 5.5 - but thanks and keep up the good work!

**Comment by zoul0813** [comment]
FYI - I updated the Laravel Deps to 5.5 in my fork's develop branch, and it appears to be working so far.  I haven't tested it thoroughly, but so far, it has not broken auth in my project.

**Comment by ArranJacques** [comment]
Sorry it took so long to address this. Initially I had other projects that needed to be worked on first, and then I just forgot.

I've updated the dependencies so it now works with Laravel 5.4 and 5.5.
