### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found

### ISSUE THREAD

**Issue by muresanandrei** [pallant/laravel-aws-cognito-auth#9]
When I try Auth::attempt() I get Base table or view not found error. I configured aws, aws-cognito-auth and also auth how it says on description but I still get this.

**Comment by zoul0813** [comment]
Do you have a DB setup with the User table, and a proper model class?

**Comment by muresanandrei** [comment]
I thought I didn't need a user table since I use cognito. Sorry I am new to everything that includes aws.So I am not sure why I need a users table when users are on aws not my db.

**Comment by zoul0813** [comment]
This package just overrides the built in Laravel user with, letting cognito authorize.  But the User model passed around still comes from your database.

**Comment by ArranJacques** [comment]
@zoul0813 thanks for the help.

I've added some additional documentation to the readme to help clarify this point.

https://github.com/pallant/laravel-aws-cognito-auth/tree/v1.1.2#users-table
